#!/bin/sh

export DATA_DIR=`pwd`"/data"
export FEED_DIR=${DATA_DIR}/"feeds"
export DATABASE=${DATA_DIR}/"ctcgator.db"

# apisecrets sets the following
# fill these in with your specific values
# export RACK_COOKIE_SECRET=
# export G_API_CLIENT=
# export G_API_SECRET=

if [ -f apisecrets ]; then
. ./apisecrets
fi

mkdir -p ${FEED_DIR}
