source :rubygems

gem 'sinatra'
gem 'json'
gem 'oauth2'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'sqlite3'
gem 'bcrypt-ruby'
gem 'libxml4r'
gem 'murmurhash3'
gem 'rubyzip'
gem 'mysql2'
gem 'dm-mysql-adapter'
